import React, { useState } from 'react';
import { Play, VolumeX, Volume2, Maximize, RotateCcw, Eye, Headphones } from 'lucide-react';
import { Trip } from '../../types';
import { Button } from '../ui/Button';
import { Modal } from '../ui/Modal';

interface VRPreviewProps {
  trip: Trip;
  onClose: () => void;
}

export const VRPreview: React.FC<VRPreviewProps> = ({ trip, onClose }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [currentScene, setCurrentScene] = useState(0);
  const [showVRModal, setShowVRModal] = useState(false);

  // Mock VR scenes data
  const vrScenes = [
    {
      id: 1,
      title: 'Arrival at Base Camp',
      description: 'Experience the breathtaking first view of your destination',
      thumbnail: trip.images[0],
      duration: '2:30',
      type: '360°'
    },
    {
      id: 2,
      title: 'Main Adventure Activity',
      description: 'Get a taste of the main activities you\'ll experience',
      thumbnail: trip.images[1] || trip.images[0],
      duration: '3:45',
      type: '360°'
    },
    {
      id: 3,
      title: 'Accommodation Tour',
      description: 'Virtual walkthrough of where you\'ll be staying',
      thumbnail: trip.images[2] || trip.images[0],
      duration: '1:50',
      type: 'VR'
    }
  ];

  const autoGeneratedReels = [
    {
      id: 1,
      title: 'Previous Travelers Highlights',
      description: 'See what past adventurers experienced on this trip',
      thumbnail: 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg',
      duration: '1:20',
      views: '2.3K'
    },
    {
      id: 2,
      title: 'Host Introduction',
      description: 'Meet your host and learn about their expertise',
      thumbnail: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
      duration: '0:45',
      views: '1.8K'
    }
  ];

  const handlePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  const handleSceneChange = (sceneIndex: number) => {
    setCurrentScene(sceneIndex);
    setIsPlaying(true);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black">
      {/* Header Controls */}
      <div className="absolute top-0 left-0 right-0 z-10 bg-gradient-to-b from-black to-transparent p-6">
        <div className="flex items-center justify-between text-white">
          <div>
            <h2 className="text-xl font-bold">{trip.title} - Virtual Preview</h2>
            <p className="text-sm opacity-75">{vrScenes[currentScene].title}</p>
          </div>
          <div className="flex items-center space-x-4">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowVRModal(true)}
              className="text-white hover:bg-white hover:bg-opacity-20"
              icon={Headphones}
            >
              VR Mode
            </Button>
            <button
              onClick={onClose}
              className="text-white hover:bg-white hover:bg-opacity-20 p-2 rounded-full transition-colors"
            >
              ✕
            </button>
          </div>
        </div>
      </div>

      {/* Main VR Viewer */}
      <div className="relative w-full h-full bg-gray-900 flex items-center justify-center">
        <div className="relative w-full h-full max-w-6xl">
          {/* 360° Image/Video Container */}
          <div className="relative w-full h-full rounded-lg overflow-hidden">
            <img
              src={vrScenes[currentScene].thumbnail}
              alt={vrScenes[currentScene].title}
              className="w-full h-full object-cover"
            />
            
            {/* VR Overlay Effects */}
            <div className="absolute inset-0 bg-gradient-to-r from-blue-500 to-purple-500 opacity-10" />
            
            {/* Play Button Overlay */}
            {!isPlaying && (
              <div className="absolute inset-0 flex items-center justify-center">
                <button
                  onClick={handlePlayPause}
                  className="w-20 h-20 bg-white bg-opacity-90 rounded-full flex items-center justify-center hover:bg-opacity-100 transition-all transform hover:scale-110 shadow-2xl"
                >
                  <Play className="w-8 h-8 text-gray-800 ml-1" />
                </button>
              </div>
            )}

            {/* VR Hotspots */}
            <div className="absolute top-1/3 left-1/4 w-4 h-4 bg-yellow-500 rounded-full animate-pulse cursor-pointer hover:scale-150 transition-transform" title="Click to explore" />
            <div className="absolute top-2/3 right-1/3 w-4 h-4 bg-yellow-500 rounded-full animate-pulse cursor-pointer hover:scale-150 transition-transform" title="Click to explore" />
            <div className="absolute bottom-1/4 left-1/2 w-4 h-4 bg-yellow-500 rounded-full animate-pulse cursor-pointer hover:scale-150 transition-transform" title="Click to explore" />
          </div>
        </div>
      </div>

      {/* Bottom Controls */}
      <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black to-transparent p-6">
        <div className="max-w-6xl mx-auto">
          {/* Progress Bar */}
          <div className="w-full bg-gray-600 rounded-full h-1 mb-4">
            <div className="bg-yellow-500 h-1 rounded-full w-1/3 transition-all duration-300" />
          </div>

          {/* Control Buttons */}
          <div className="flex items-center justify-between text-white">
            <div className="flex items-center space-x-4">
              <button
                onClick={handlePlayPause}
                className="p-3 bg-white bg-opacity-20 rounded-full hover:bg-opacity-30 transition-colors"
              >
                {isPlaying ? (
                  <div className="w-4 h-4 bg-white rounded-sm" />
                ) : (
                  <Play className="w-4 h-4" />
                )}
              </button>
              
              <button
                onClick={() => setIsMuted(!isMuted)}
                className="p-3 bg-white bg-opacity-20 rounded-full hover:bg-opacity-30 transition-colors"
              >
                {isMuted ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}
              </button>

              <button className="p-3 bg-white bg-opacity-20 rounded-full hover:bg-opacity-30 transition-colors">
                <RotateCcw className="w-4 h-4" />
              </button>

              <span className="text-sm opacity-75">
                {vrScenes[currentScene].duration} • {vrScenes[currentScene].type}
              </span>
            </div>

            <div className="flex items-center space-x-4">
              <button className="p-3 bg-white bg-opacity-20 rounded-full hover:bg-opacity-30 transition-colors">
                <Maximize className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Scene Selection */}
          <div className="mt-6">
            <h3 className="text-white text-sm font-medium mb-3">VR Scenes</h3>
            <div className="flex space-x-4 overflow-x-auto">
              {vrScenes.map((scene, index) => (
                <button
                  key={scene.id}
                  onClick={() => handleSceneChange(index)}
                  className={`flex-shrink-0 w-32 h-20 rounded-lg overflow-hidden border-2 transition-all ${
                    currentScene === index ? 'border-yellow-500' : 'border-transparent'
                  }`}
                >
                  <img
                    src={scene.thumbnail}
                    alt={scene.title}
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute inset-0 bg-black bg-opacity-40 flex items-center justify-center">
                    <div className="text-center">
                      <div className="text-white text-xs font-medium">{scene.type}</div>
                      <div className="text-white text-xs opacity-75">{scene.duration}</div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Auto-Generated Reels */}
          <div className="mt-6">
            <h3 className="text-white text-sm font-medium mb-3">Trip Highlights</h3>
            <div className="flex space-x-4 overflow-x-auto">
              {autoGeneratedReels.map((reel) => (
                <button
                  key={reel.id}
                  className="flex-shrink-0 w-32 h-20 rounded-lg overflow-hidden border border-gray-600 hover:border-yellow-500 transition-colors"
                >
                  <img
                    src={reel.thumbnail}
                    alt={reel.title}
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute inset-0 bg-black bg-opacity-40 flex items-center justify-center">
                    <Play className="w-6 h-6 text-white" />
                  </div>
                  <div className="absolute bottom-1 left-1 right-1">
                    <div className="text-white text-xs font-medium truncate">{reel.title}</div>
                    <div className="text-white text-xs opacity-75">{reel.duration} • {reel.views} views</div>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* VR Mode Modal */}
      <Modal
        isOpen={showVRModal}
        onClose={() => setShowVRModal(false)}
        title="VR Experience"
        maxWidth="max-w-md"
      >
        <div className="space-y-6">
          <div className="text-center">
            <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Headphones className="w-8 h-8 text-purple-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Enhanced VR Experience</h3>
            <p className="text-gray-600">
              For the best experience, use VR headsets or enable gyroscope on your mobile device.
            </p>
          </div>

          <div className="space-y-3">
            <div className="flex items-center p-3 bg-gray-50 rounded-lg">
              <Eye className="w-5 h-5 text-blue-600 mr-3" />
              <div>
                <div className="font-medium text-gray-900">360° View</div>
                <div className="text-sm text-gray-600">Look around by moving your device</div>
              </div>
            </div>
            
            <div className="flex items-center p-3 bg-gray-50 rounded-lg">
              <Headphones className="w-5 h-5 text-green-600 mr-3" />
              <div>
                <div className="font-medium text-gray-900">Spatial Audio</div>
                <div className="text-sm text-gray-600">Use headphones for immersive sound</div>
              </div>
            </div>
          </div>

          <div className="flex space-x-3">
            <Button variant="outline" onClick={() => setShowVRModal(false)} className="flex-1">
              Continue Viewing
            </Button>
            <Button variant="primary" className="flex-1">
              Enable VR Mode
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};